name: resume-optimizer-studio
services:
- name: web
  source_dir: /
  github:
    repo: harshajustin/resume-optimizer-studio
    branch: production
  run_command: npm run preview
  build_command: npm install && npm run build
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  health_check:
    http_path: /
  envs:
  - key: NODE_ENV
    value: production
